// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/hello.proto

package me.minikuma.v1;

public final class HelloGrpcProto {
  private HelloGrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_minikuma_v1_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_minikuma_v1_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_minikuma_v1_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_minikuma_v1_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016v1/hello.proto\022\016me.minikuma.v1\"#\n\014Hell" +
      "oRequest\022\023\n\013client_name\030\001 \001(\t\"(\n\rHelloRe" +
      "sponse\022\027\n\017welcome_message\030\001 \001(\t2[\n\014Hello" +
      "Service\022K\n\nunaryHello\022\034.me.minikuma.v1.H" +
      "elloRequest\032\035.me.minikuma.v1.HelloRespon" +
      "se\"\000B\022B\016HelloGrpcProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_me_minikuma_v1_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_minikuma_v1_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_minikuma_v1_HelloRequest_descriptor,
        new java.lang.String[] { "ClientName", });
    internal_static_me_minikuma_v1_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_minikuma_v1_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_minikuma_v1_HelloResponse_descriptor,
        new java.lang.String[] { "WelcomeMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
