// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/hello.proto

package me.minikuma.v1;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.minikuma.v1.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_name = 1;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string client_name = 1;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();
}
