// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2/product.proto

package me.minikuma.v2;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.minikuma.v2.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 price = 3;</code>
   * @return The price.
   */
  int getPrice();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();
}
