// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2/product.proto

package me.minikuma.v2;

public final class ProductGrpcProto {
  private ProductGrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_minikuma_v2_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_minikuma_v2_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_minikuma_v2_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_minikuma_v2_ProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020v2/product.proto\022\016me.minikuma.v2\"$\n\016Pr" +
      "oductRequest\022\022\n\nproduct_id\030\001 \001(\003\"L\n\017Prod" +
      "uctResponse\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\r\n" +
      "\005price\030\003 \001(\005\022\020\n\010quantity\030\004 \001(\0052e\n\016Produc" +
      "tService\022S\n\016getProductById\022\036.me.minikuma" +
      ".v2.ProductRequest\032\037.me.minikuma.v2.Prod" +
      "uctResponse\"\000B\024B\020ProductGrpcProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_me_minikuma_v2_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_minikuma_v2_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_minikuma_v2_ProductRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_me_minikuma_v2_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_minikuma_v2_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_minikuma_v2_ProductResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
