// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2/product.proto

package me.minikuma.v2;

public interface ProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.minikuma.v2.ProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  long getProductId();
}
