// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/hello.proto

package me.minikuma.v1;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.minikuma.v1.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string welcome_message = 1;</code>
   * @return The welcomeMessage.
   */
  java.lang.String getWelcomeMessage();
  /**
   * <code>string welcome_message = 1;</code>
   * @return The bytes for welcomeMessage.
   */
  com.google.protobuf.ByteString
      getWelcomeMessageBytes();
}
